name: "build names"
outputs:
  short_sha:
    value: ${{ steps.sha.outputs.SHORT_SHA }}
  pretty_branch_name:
    value: ${{ steps.branch.outputs.NAME }}
  artifact_prefix:
    value: ${{ steps.branch.outputs.NAME }}-${{ steps.sha.outputs.SHORT_SHA }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Set short sha output
      id: sha
      run: echo "SHORT_SHA=$(git rev-parse --short=11 HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Set archive name output
      id: branch
      run: |
        export PRETTY_BRANCH_NAME=$(tr '/' '-' <<< ${{ github.ref_name }})
        echo "NAME=${PRETTY_BRANCH_NAME}" >> $GITHUB_OUTPUT
      shell: bash