name: Install dependencies
description: install all project dependencies.

inputs:
  node_version:
    description: Node version used to install dependencies
    required: false
    default: '16.16'
  npm_version:
    description: NPM version used to install dependencies
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
    - run: npm i -g npm@${{ inputs.npm_version }}
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      run: npm ci --prefer-offline
      shell: bash
