name: Terraform Action

inputs:
  action:
    description: 'Terraform action to run e.g plan'
    required: true
    type: string
  project:
    description: 'Terraform project'
    required: true
    type: string
  environment:
    description: 'Terraform environment'
    required: true
    type: string
  component:
    description: 'Terraform component'
    required: true
    type: string
  group:
    description: 'Terraform group'
    required: true
    type: string
  bucket-prefix:
    description: 'AWS Terraform bucket used for TF state'
    required: true
    type: string
  region:
    description: 'AWS region'
    required: true
    type: string
  terraform_version:
    type: number
    default: '1.3.7'
    description: Terraform Version to install on runner
  terraform_args:
    type: string
    default: ''
    description: Additional Terraform arguments
  terraform_directory:
    type: string
    default: '.'
    description: Directory location of Terraform

runs:
  using: 'composite'
  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version:  ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Terraform init and plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        mkdir -p plans/${{ inputs.environment }}
        ./bin/terraform.sh --action ${{ inputs.action }} --project ${{ inputs.project }} --environment ${{ inputs.environment }}  --component ${{ inputs.component }} --group ${{ inputs.group }} --bucket-prefix ${{ inputs.bucket-prefix }} --region ${{ inputs.region }} --compact-warnings --no-color -- ${{ inputs.terraform_args }} | tee plans/${{ inputs.environment }}/${{ inputs.component }}-plan.txt
      shell: bash

    - name: Save Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.environment }}-${{ inputs.component }}"
        path: "${{ inputs.terraform_directory }}/plans/${{ inputs.environment }}/${{ inputs.component }}-plan.txt"
        retention-days: 7
