name: Terraform Security Scan

inputs:
  github_token:
    required: true
    type: string
  terraform_version:
    required: false
    type: string
    description: Terraform version
    default: '1.3.7'
  path:
    required: false
    type: string
    description: Target directory in which to run tfsec command
    default: 'components/'
  

runs:
  using: 'composite'
  steps:

    - name: Checkout the repository to the runner
      uses: actions/checkout@v3

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v3.0.0
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform init
      id: init
      run: terraform init
      shell: bash

    - name: Group all .tf files under target directory
      run: |
        find ${{ inputs.path }} -mindepth 2 -type f \
          -print -exec cp -r {} ${{ inputs.path }} \;
        ls -la ${{ inputs.path }}
      shell: bash
      
    - name: Terraform Security scanning tfsec
      id: tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ${{ inputs.path }}
        additional_args: -e .terraform --concise-output --out .tfsec_output
        # format: sarif
        soft_fail: true
        github_token: '${{ inputs.github_token }}'
        
    - name: Print concise output of tfsec scan
      run: |
        cat .tfsec_output
      shell: bash
