name: Check PR title

on:
  pull_request:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    uses: dvsa/.github/.github/workflows/conventional-commits.yaml@v5
    with:
      title: ${{ github.event.pull_request.title }}
