name: CI

on:
  push:

jobs:
  lint:
    uses: dvsa/.github/.github/workflows/nodejs-lint.yaml@v2.3

  test:
    uses: dvsa/.github/.github/workflows/nodejs-test.yaml@v2.3

  security:
    uses: dvsa/.github/.github/workflows/nodejs-security.yaml@v2.3
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-names:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      short_sha: ${{ steps.sha.outputs.SHORT_SHA }}
      pretty_branch_name: ${{ steps.branch.outputs.NAME }}
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Set short sha output
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short=11 HEAD)" >> $GITHUB_OUTPUT
      - name: Set archive name output
        id: branch
        run: |
          export PRETTY_BRANCH_NAME=$(tr '/' '-' <<< "$BRANCH_NAME")
          echo "NAME=${PRETTY_BRANCH_NAME}" >> $GITHUB_OUTPUT

  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v2.3
    needs: [ build-names ]
    with:
      upload_artifact: ${{ github.ref_name == 'main' }}
      build_folder: dist
      build_command: build:prod

  upload-to-s3:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    uses: dvsa/.github/.github/workflows/upload-to-s3.yaml@v2.3
    needs: [ lint, test, build, build-names ]
    with:
      environment: dev
      short_commit: ${{ needs.build-names.outputs.short_sha }}
      artifact: dist.zip
      bucket_key: <location-in-bucket>/${{ needs.build-names.outputs.pretty_branch_name }}.zip
    permissions:
      id-token: write
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

  update-lambda-code:
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    uses: dvsa/.github/.github/workflows/update-lambda-function.yaml@v2.3
    needs: [ build-names, build, upload-s3 ]
    with:
      environment: dev
      lambda_function_name: <function-name>
      bucket_key: <location-in-bucket>/${{ needs.build-names.outputs.pretty_branch_name }}.zip
    permissions:
      id-token: write
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}