name: NPM Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: dvsa/.github/.github/workflows/nodejs-publish.yaml@v4.0.0
    with:
      node-version: '16.x'
      download_artifact: true
      build_folder: package
      build_folder_path: dist
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
