name: NPM Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: dvsa/.github/.github/workflows/nodejs-publish.yaml@v4.1.1
    with:
      node-version: '18.x'
      download-artifact: true
      build-folder: package
      build-folder-path: dist
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
