name: PHP Unit Tests 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'
 
jobs:
  static:
    uses: dvsa/.github/.github/workflows/php-tests.yml@v3.2.0
    with: 
     php_versions: "[\"7.4\",\"8.0\"]"
