name: Static analysis

on:
  push:
    branches: [ $default-branch  ]
  pull_request:
    branches: [ $default-branch ]
  schedule:
    - cron: '0 0 * * 1'
 
jobs:
  static:
    uses: dvsa/.github/.github/workflows/php-static.yml@v4.0.0
    
