name: PHP Unit Tests 

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  schedule:
    - cron: '0 0 * * 1'
 
jobs:
  static:
    uses: dvsa/.github/.github/workflows/php-tests.yml@v5.0.6
    with: 
     php-versions: "[\"8.2\","8.3","8.4"]"
