name: aws-cli

inputs:
  gatling_report_path:
    type: string
    description: Path of Gatling Reports
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate Job Summary 
      uses: actions/github-script@v7
      env:
        TEST_PATH: ${{ inputs.gatling_report_path }}
      with:
        script: |
          const fs = require('fs')
          const gatling_report = process.env.TEST_PATH
          const lastRuns = fs.readFileSync(`${gatling_report}/lastRun.txt`).toString().trim().split('\n');
          for(const run of lastRuns) {
              const results = JSON.parse(fs.readFileSync(`${gatling_report}/${run}/js/stats.json`).toString());
              let tableContent = [
                  [
                      {data: 'Request', header: true}, 
                      {data: 'Success ✅', header: true}, 
                      {data: 'Errors ❌', header: true}, 
                      {data: 'Min', header: true},
                      {data: 'Max', header: true},
                      {data: 'Avg.', header: true},
                      {data: 'Std. Dev.', header: true},
                      {data: 'RPS', header: true},
                  ]
              ];
              
              for(const result in results.contents) {
                  const requestMetrics = results.contents[result].stats;
                  tableContent.push([
                      requestMetrics.name,
                      requestMetrics.numberOfRequests.ok.toString(),
                      requestMetrics.numberOfRequests.ko.toString(),
                      requestMetrics.minResponseTime.total.toString(),
                      requestMetrics.maxResponseTime.total.toString(),
                      requestMetrics.meanResponseTime.total.toString(),
                      requestMetrics.standardDeviation.total.toString(),
                      requestMetrics.meanNumberOfRequestsPerSecond.total.toString(),
                  ]);
              }
              await core.summary
                  .addHeading(`Results for Performance Test`)                    
                  .addTable(tableContent)
                  .addQuote('All times are in millisecond (ms). RPS means "Requests per Second"')
                  .write()
          }