name: Conventional Commits

on:
  workflow_call:
    inputs:
      title:
        description: "PR title"
        type: string
        required: true

permissions:
  contents: read

concurrency:
  group: check-pr-title-${{ github.event.pull_request.id || github.run_id }}
  cancel-in-progress: true

jobs:
  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    env:
      INPUT: ${{ inputs.title || github.event.pull_request.title }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: dvsa/.github
          ref: ${{ github.workflow_sha }}

      - name: Validate input
        uses: ./.github/actions/commitlint
        with:
          input: ${{ env.INPUT }}
