name: Tests

on:
  workflow_call:
    inputs:
      php-versions:
        required: true
        type: string
      fail-fast:
        required: false
        default: true
        type: boolean
      phpunit-config-file:
        required: false
        type: string
      composer-version:
        required: false
        type: string
        default: 'v2'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        php: ${{ fromJSON(inputs.php-versions) }}

    name: PHP test ${{ matrix.php }}

    env:
      PHPUNIT_CONFIG_FILE: ${{ inputs.phpunit-config-file && format('-c "{0}"', inputs.phpunit-config-file) || '' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:${{ inputs.composer-version }}
          coverage: none

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-progress --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit $PHPUNIT_CONFIG_FILE
