name: Tests

on:
  workflow_call:
   inputs:
    php-versions:
     required: true
     type: string

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ${{ fromJSON(inputs.php-versions) }}
        
    name: PHP test ${{ matrix.php }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --optimize-autoloader --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
