name: Python Linting

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff and save results
        run: |
          mkdir -p logs
          timestamp=$(date +"%Y%m%d_%H%M%S")
          ruff check . > logs/lint_result_${timestamp}.txt
      - name: Run Ruff Format
        run: ruff format --check .
      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint-results
          path: logs/lint_result_*.txt
